<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Project_3</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="dist\**" />
    <Compile Remove="Properties\Frontend\**" />
    <Content Remove="dist\**" />
    <Content Remove="Properties\Frontend\**" />
    <EmbeddedResource Remove="dist\**" />
    <EmbeddedResource Remove="Properties\Frontend\**" />
    <None Remove="dist\**" />
    <None Remove="Properties\Frontend\**" />
    <_WebToolingArtifacts Remove="Properties\Frontend\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.18" />
    <PackageReference Include="OpenXmlPowerTools" Version="4.5.3.2" />
    <PackageReference Include="WebMotions.Fake.Authentication.JwtBearer" Version="9.0.0" />
    
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CountryExplorer.Application\CountryExplorer.Application.csproj" />
    <ProjectReference Include="..\CountryExplorer.Infrastructure\CountryExplorer.Infrastructure.csproj" />
  </ItemGroup>

</Project>